### ISSUE TITLE
Calendar View TODO

### ISSUE THREAD

**Issue by deondreE** [deondreE/UiBox#1]
# These Things need to be done
- [ ]  Add an info overlay.
- [x]  Allow users to create events on the calendar.
- [ ] Make calendar view turn on and off with animation.
- [ ] Make function to return all days with events and what they are.
- [ ] Make notification wrapper for all the event based dates.
- [ ] Add function to run on a specified day `do this on a day`.

# If you are a amazing person :)

- [ ] Sync with actual apple calendar.
- [ ] Sync with Google Calendar.
- [ ] Make Calendar have multiple tabs: ex: `work`, `school`.

**Comment by deondreE** [comment]
Highlighting issues for the highlightWeekends. Returning values that are not weekends.

### Image

![Highlight Issues](https://github.com/deondreE/UiBox/assets/67658523/a908f159-bb8f-4c1d-9bda-f93a44e327a1)

**Comment by deondreE** [comment]
- [ ] Fix where the add event button is in the view of the calendar
