### ISSUE TITLE
ComboBox Issues

### ISSUE THREAD

**Issue by deondreE** [deondreE/UiBox#2]
# issues

Currently the combo box content is wayy below where it should be.
--- 
### Current Look
![Screenshot 2024-01-06 at 4 04 35 PM](https://github.com/deondreE/UiBox/assets/67658523/a7ef62b8-429b-4231-8945-e243c4632488)

> Should be directly underneath the item.

# TODO 

- [x] Fix the core button to change to what is chosen.
- [x] Fix the core position of where the content comes from.
- [x] If there is more then 3 indexes, render inside of a `ScrollView`.
- [x] Make sure it works with larger item sets.
- [x] Move the search bar into it's own stand alone component.
- [ ] Fix Searchbar to actually function.

**Comment by deondreE** [comment]
Now the component shows up at the top left corner clearly something is not right here.

# image
![Screenshot 2024-01-06 at 5 32 22 PM](https://github.com/deondreE/UiBox/assets/67658523/32154b78-d85f-455b-a75e-97d8d8336301)
